name: Node.js CI

on: [push]

jobs:
  lint:
    # Checkout, install dependencies, and lint
    name: Lint code base

    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Install dependencies
        working-directory: ./js
        run: npm install

      - name: Typecheck
        working-directory: ./js
        run: tsc --noEmit

      - name: Lint
        working-directory: ./js
        run: npm run lint
